#!/usr/bin/env bash
# Purpl Brain — beta setup
# Prompts for required credentials and writes apps/api/.env
# Usage: bash setup.sh

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RESET='\033[0m'

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║        Purpl Brain — Setup               ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${RESET}"
echo ""
echo "This script will:"
echo "  1. Check Docker is running"
echo "  2. Collect your credentials"
echo "  3. Write apps/api/.env"
echo "  4. Start infrastructure (Redis, Neo4j, Qdrant)"
echo "  5. Seed your first GitHub repo"
echo ""

# ── Docker check ──────────────────────────────────────────────────────────────
if ! docker info &>/dev/null; then
  echo "❌  Docker is not running. Start Docker Desktop and re-run this script."
  exit 1
fi
echo -e "${GREEN}✓ Docker is running${RESET}"

# ── Credentials ───────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Required credentials ─────────────────────────────────${RESET}"
echo ""

read -rp "GitHub personal access token (repo read scope): " GITHUB_TOKEN
if [[ -z "$GITHUB_TOKEN" ]]; then
  echo "❌  GitHub token is required."
  exit 1
fi

read -rp "Anthropic API key (sk-ant-...): " ANTHROPIC_API_KEY
if [[ -z "$ANTHROPIC_API_KEY" ]]; then
  echo "❌  Anthropic API key is required."
  exit 1
fi

read -rp "GitHub repo to track (e.g. encode/httpx): " GITHUB_REPO
if [[ -z "$GITHUB_REPO" ]]; then
  echo "❌  GitHub repo is required."
  exit 1
fi

# Derive project_id from repo (org_repo format)
PROJECT_ID="${GITHUB_REPO//\//_}"

# ── Optional sources ─────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Optional sources (press Enter to skip) ───────────────${RESET}"
echo ""

read -rp "Slack bot token (xoxb-... or leave blank): " SLACK_BOT_TOKEN
read -rp "Slack app token (xapp-... or leave blank): " SLACK_APP_TOKEN
read -rp "Slack channel IDs to monitor (comma-separated or blank): " SLACK_CHANNEL_IDS
read -rp "Jira base URL (e.g. https://myorg.atlassian.net or blank): " JIRA_BASE_URL
read -rp "Jira webhook secret (or blank): " JIRA_WEBHOOK_SECRET

# ── Write .env ────────────────────────────────────────────────────────────────
ENV_FILE="apps/api/.env"

cat > "$ENV_FILE" << ENVEOF
# Generated by setup.sh on $(date)

# ── Infrastructure ─────────────────────────────────────────────────────────
REDIS_URL=redis://localhost:6379
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=password
QDRANT_URL=http://localhost:6333

# ── LLM (Claude API) ───────────────────────────────────────────────────────
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
LLM_PROVIDER=anthropic
LLM_MODEL=claude-haiku-4-5-20251001
EXTRACTION_MODEL=claude-haiku-4-5-20251001

# ── GitHub ─────────────────────────────────────────────────────────────────
GITHUB_TOKEN=${GITHUB_TOKEN}
GITHUB_WEBHOOK_SECRET=local-dev-secret
DEFAULT_PROJECT_ID=${PROJECT_ID}

# ── Slack (optional — leave blank to disable) ──────────────────────────────
SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
SLACK_APP_TOKEN=${SLACK_APP_TOKEN:-}
SLACK_CHANNEL_IDS=${SLACK_CHANNEL_IDS:-}
SLACK_DEFAULT_PROJECT=${PROJECT_ID}

# ── Jira (optional — leave blank to disable) ───────────────────────────────
JIRA_BASE_URL=${JIRA_BASE_URL:-https://jira.example.com}
JIRA_WEBHOOK_SECRET=${JIRA_WEBHOOK_SECRET:-}
JIRA_DEFAULT_PROJECT=${PROJECT_ID}

# ── Tuning ─────────────────────────────────────────────────────────────────
DRIFT_SEMANTIC_THRESHOLD=0.55
DRIFT_TOP_K=3
CONTEXT_BUDGET=6000
ENVEOF

echo ""
echo -e "${GREEN}✓ Written apps/api/.env${RESET}"

# ── Copy to MCP env ───────────────────────────────────────────────────────────
cat > "apps/mcp/.env" << MCPEOF
BRAIN_API_URL=http://localhost:3001
BRAIN_API_KEY=
MCPEOF
echo -e "${GREEN}✓ Written apps/mcp/.env${RESET}"

# ── Start infrastructure ──────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Starting infrastructure ──────────────────────────────${RESET}"
docker compose up -d
echo -e "${GREEN}✓ Redis, Neo4j, Qdrant started${RESET}"

# ── Install deps ──────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Installing dependencies ──────────────────────────────${RESET}"
npm install --silent
echo -e "${GREEN}✓ Dependencies installed${RESET}"

# ── Seed GitHub ───────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Seeding GitHub repo: ${GITHUB_REPO} ───────────────────${RESET}"
echo "  (fetches last 50 PRs — takes ~30 seconds)"
npm run seed:github -w apps/api -- --repo "$GITHUB_REPO" --limit 50
echo -e "${GREEN}✓ GitHub events seeded${RESET}"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║  Setup complete!                                         ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Start the API + workers (new terminal):"
echo "     npm run dev -w apps/api"
echo "     npm run worker:normalizer -w apps/api"
echo "     npm run worker:extractor -w apps/api"
echo "     npm run worker:brain-writer -w apps/api"
echo "     npm run worker:drift -w apps/api"
echo ""
echo "  2. Start the chat UI (new terminal):"
echo "     npm run dev -w apps/web"
echo "     open http://localhost:3000"
echo ""
echo "  3. Query the brain from Claude Code:"
echo "     The MCP server is already configured in .claude/settings.json"
echo "     Ask Claude: \"What decisions were made in ${GITHUB_REPO}?\""
echo ""
if [[ -z "$SLACK_BOT_TOKEN" && -z "$JIRA_BASE_URL" ]]; then
  echo -e "  ${YELLOW}Optional: add Slack/Jira credentials to apps/api/.env to enable${RESET}"
  echo -e "  ${YELLOW}those sources, then run:${RESET}"
  echo "     npm run worker:slack -w apps/api"
  echo "     npm run seed:jira -w apps/api -- --project ${PROJECT_ID}"
  echo ""
fi
