#!/usr/bin/env bash
# Purpl Brain — pre-built image setup (no Node.js required)
# Uses GHCR images. Run this instead of setup.sh if you don't have Node.js 20+.
#
# Usage: bash setup-prebuilt.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
RESET='\033[0m'

REPO_RAW="https://raw.githubusercontent.com/skalrn/purpl_brain/main"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║     Purpl Brain — Pre-built Setup        ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${RESET}"
echo ""
echo "This sets up purpl-brain using pre-built Docker images."
echo "No Node.js required."
echo ""

# ── Docker check ──────────────────────────────────────────────────────────────
if ! docker info &>/dev/null; then
  echo -e "${RED}❌  Docker is not running. Start Docker Desktop and re-run.${RESET}"
  exit 1
fi
echo -e "${GREEN}✓ Docker is running${RESET}"

if ! docker compose version &>/dev/null; then
  echo -e "${RED}❌  Docker Compose V2 is required. Update Docker Desktop or install the compose plugin.${RESET}"
  exit 1
fi
echo -e "${GREEN}✓ Docker Compose V2${RESET}"

# ── Download compose file if not present ─────────────────────────────────────
if [[ ! -f "docker-compose.prod.yml" ]]; then
  echo ""
  echo "Downloading docker-compose.prod.yml..."
  curl -fsSL "$REPO_RAW/docker-compose.prod.yml" -o docker-compose.prod.yml
  echo -e "${GREEN}✓ docker-compose.prod.yml downloaded${RESET}"
else
  echo -e "${GREEN}✓ docker-compose.prod.yml found${RESET}"
fi

# ── LLM provider ─────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── LLM provider ─────────────────────────────────────────${RESET}"
echo ""
echo "  1) Ollama  — runs locally, no API key needed. Slower (~14s/query)."
echo "               Requires: ollama pull llama3.1:8b nomic-embed-text:v1.5"
echo "  2) Anthropic — cloud API, fast (~2s/query). Requires an API key."
echo ""
read -rp "Choose provider [1/2, default 1]: " LLM_CHOICE
LLM_CHOICE="${LLM_CHOICE:-1}"

ANTHROPIC_API_KEY=""
LLM_PROVIDER="ollama"

if [[ "$LLM_CHOICE" == "2" ]]; then
  LLM_PROVIDER="anthropic"
  read -rp "Anthropic API key (sk-ant-...): " ANTHROPIC_API_KEY
  if [[ -z "$ANTHROPIC_API_KEY" ]]; then
    echo -e "${RED}❌  Anthropic API key is required.${RESET}"
    exit 1
  fi
else
  if ! curl -sf http://localhost:11434/api/tags >/dev/null 2>&1; then
    echo -e "${YELLOW}⚠️   Ollama not detected at http://localhost:11434.${RESET}"
    echo "    Install from https://ollama.ai, then pull the required models:"
    echo "      ollama pull llama3.1:8b"
    echo "      ollama pull nomic-embed-text:v1.5"
    echo ""
    read -rp "Continue anyway? [y/N]: " CONTINUE
    [[ "${CONTINUE:-n}" =~ ^[Yy]$ ]] || exit 1
  else
    echo -e "${GREEN}✓ Ollama is running${RESET}"
    MISSING_MODELS=()
    for MODEL in "llama3.1:8b" "nomic-embed-text:v1.5"; do
      if ! curl -sf http://localhost:11434/api/tags | grep -q "\"$MODEL\"" 2>/dev/null; then
        MISSING_MODELS+=("$MODEL")
      fi
    done
    if [[ ${#MISSING_MODELS[@]} -gt 0 ]]; then
      echo -e "${YELLOW}⚠️   Missing Ollama models: ${MISSING_MODELS[*]}${RESET}"
      echo "    Pull them with:"
      for M in "${MISSING_MODELS[@]}"; do echo "      ollama pull $M"; done
      echo ""
      read -rp "Continue anyway? [y/N]: " CONTINUE
      [[ "${CONTINUE:-n}" =~ ^[Yy]$ ]] || exit 1
    else
      echo -e "${GREEN}✓ Required Ollama models present${RESET}"
    fi
  fi
fi

# ── Project name ──────────────────────────────────────────────────────────────
echo ""
read -rp "Project name (e.g. my_team_auth_service): " PROJECT_ID
if [[ -z "$PROJECT_ID" ]]; then
  echo -e "${RED}❌  Project name is required.${RESET}"
  exit 1
fi
PROJECT_ID="${PROJECT_ID//[^a-zA-Z0-9]/_}"

# ── Generate credentials ──────────────────────────────────────────────────────
API_KEY="pbk_$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)"
NEO4J_PASSWORD_GEN="$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 16)"
SESSION_SECRET_GEN="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | base64 | head -c 44)"

# ── Write .env ────────────────────────────────────────────────────────────────
cat > ".env" << ENVEOF
# Generated by setup-prebuilt.sh on $(date)

# ── Infrastructure ──────────────────────────────────────────────────────────
NEO4J_AUTH=neo4j/${NEO4J_PASSWORD_GEN}
NEO4J_USER=neo4j
NEO4J_PASSWORD=${NEO4J_PASSWORD_GEN}
QDRANT_COLLECTION=brain_chunks
QDRANT_VECTOR_SIZE=768

# ── LLM ────────────────────────────────────────────────────────────────────
LLM_PROVIDER=${LLM_PROVIDER}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
LLM_MODEL=$([ "$LLM_PROVIDER" = "anthropic" ] && echo "claude-sonnet-4-6" || echo "llama3.1:8b")
EXTRACTION_MODEL=$([ "$LLM_PROVIDER" = "anthropic" ] && echo "claude-haiku-4-5-20251001" || echo "llama3.1:8b")
OLLAMA_FAST_MODEL=llama3.1:8b
OLLAMA_SMART_MODEL=llama3.1:8b
OLLAMA_EMBED_MODEL=nomic-embed-text:v1.5
OLLAMA_BASE_URL=http://host.docker.internal:11434/v1

# ── Auth ────────────────────────────────────────────────────────────────────
DEV_API_KEY=${API_KEY}
SESSION_SECRET=${SESSION_SECRET_GEN}
SESSION_COOKIE_SECURE=false

# ── Project ─────────────────────────────────────────────────────────────────
DEFAULT_PROJECT_ID=${PROJECT_ID}

# ── Tuning ──────────────────────────────────────────────────────────────────
DRIFT_SEMANTIC_THRESHOLD=0.55
DRIFT_TOP_K=3
QUERY_TOP_K=20
QUERY_CONTEXT_BUDGET=$([ "$LLM_PROVIDER" = "anthropic" ] && echo "12000" || echo "6000")
QUERY_MIN_SCORE=0.50
ENVEOF

echo -e "${GREEN}✓ Written .env${RESET}"

# ── Download and patch hooks ──────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Setting up Claude Code hooks ─────────────────────────${RESET}"
mkdir -p .claude/hooks
for HOOK in "check-brain-decisions.sh" "mid-session-brain-check.sh"; do
  curl -fsSL "$REPO_RAW/.claude/hooks/$HOOK" -o ".claude/hooks/$HOOK"
  sed -i.bak "s/PROJECT_ID=\"skalrn_purpl_brain\"/PROJECT_ID=\"${PROJECT_ID}\"/" ".claude/hooks/$HOOK"
  rm -f ".claude/hooks/${HOOK}.bak"
  chmod +x ".claude/hooks/$HOOK"
done
echo -e "${GREEN}✓ Hooks downloaded and patched with project ID: ${PROJECT_ID}${RESET}"

# ── Port conflict check ───────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Checking ports ───────────────────────────────────────${RESET}"
MCP_PORT_CHECK="${MCP_HOST_PORT:-3002}"
PORTS_OK=true
for PORT in 3001 "$MCP_PORT_CHECK"; do
  if lsof -i ":${PORT}" >/dev/null 2>&1; then
    PROCESS=$(lsof -ti ":${PORT}" | xargs ps -p 2>/dev/null | tail -1 | awk '{print $4}' || echo "unknown")
    echo -e "${RED}❌  Port ${PORT} is already in use by: ${PROCESS}${RESET}"
    PORTS_OK=false
  fi
done
if [[ "$PORTS_OK" == "false" ]]; then
  echo ""
  echo "    Stop the conflicting process and re-run, or override the MCP port:"
  echo "      MCP_HOST_PORT=3003 bash setup-prebuilt.sh"
  exit 1
fi
echo -e "${GREEN}✓ Ports 3001 and 3002 are available${RESET}"

# ── Start services ────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Starting services (pulling images on first run) ──────${RESET}"
echo "(First run pulls images — typically 2-3 minutes)"
if ! docker compose -f docker-compose.prod.yml up -d; then
  echo -e "${RED}❌  Docker Compose failed. Check logs: docker compose -f docker-compose.prod.yml logs${RESET}"
  exit 1
fi
echo -e "${GREEN}✓ All services started${RESET}"

# ── Wait for API ──────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Waiting for API to be healthy ────────────────────────${RESET}"
API_TIMEOUT=120
API_ELAPSED=0
until curl -sf http://localhost:3001/health >/dev/null 2>&1; do
  if [[ $API_ELAPSED -ge $API_TIMEOUT ]]; then
    echo -e "${RED}❌  API did not become healthy within ${API_TIMEOUT}s.${RESET}"
    echo "    Check logs: docker compose -f docker-compose.prod.yml logs api"
    exit 1
  fi
  sleep 2
  API_ELAPSED=$((API_ELAPSED + 2))
done
echo -e "${GREEN}✓ API is healthy (${API_ELAPSED}s)${RESET}"

# ── Print MCP config ──────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║  Add this to ~/.claude/settings.json                     ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""
cat << MCPCONFIG
{
  "mcpServers": {
    "purpl-brain": {
      "url": "http://localhost:3002/mcp"
    }
  }
}
MCPCONFIG

# ── Print CLAUDE.md snippet ───────────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║  Add this to CLAUDE.md in your project repo              ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""
cat << CLAUDEMD
## Brain (purpl-brain MCP)

The purpl-brain MCP is connected. Use \`project_id: ${PROJECT_ID}\` in all tool calls.

- **Session start:** call \`brain_query\` to recall prior decisions and open drift alerts.
- **Before a significant change:** call \`brain_analyze_impact\`.
- **When a decision is made:** call \`brain_log_decision\`.
- **When something unexpected surfaces:** call \`brain_log_signal\`.
CLAUDEMD

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║  Setup complete                                          ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""
echo "  API key:    ${API_KEY}"
echo "  Project ID: ${PROJECT_ID}"
echo "  API:        http://localhost:3001"
echo "  MCP:        http://localhost:3002/mcp"
echo ""
echo "Next steps:"
echo "  1. Paste the MCP config above into ~/.claude/settings.json"
echo "  2. Paste the CLAUDE.md snippet into your project repo"
echo "  3. Open a Claude Code session — brain tools are now available"
echo ""
if [[ "$LLM_PROVIDER" == "ollama" ]]; then
echo -e "${YELLOW}  ⏱  Ollama query latency: ~14s p50, ~28s p95. This is normal.${RESET}"
echo -e "${YELLOW}     Switch to LLM_PROVIDER=anthropic in .env for ~2s latency.${RESET}"
fi
echo ""
echo -e "${YELLOW}Tail logs:${RESET}"
echo "  docker compose -f docker-compose.prod.yml logs -f api extractor brain-writer"
echo ""
