#!/usr/bin/env bash
# Purpl Brain — setup
# Gets the agent memory loop working in ~5 minutes.
# GitHub, Slack, and Jira can be connected afterwards.
#
# Usage: bash setup.sh

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
RESET='\033[0m'

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║        Purpl Brain — Setup               ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${RESET}"
echo ""
echo "This gets the agent memory loop working:"
echo "  1. Collect your Anthropic API key and a project name"
echo "  2. Build the MCP server"
echo "  3. Start infrastructure (Redis, Neo4j, Qdrant)"
echo "  4. Print the Claude Code / Cursor config to paste"
echo ""
echo -e "${YELLOW}GitHub, Slack, and Jira are optional — connect them later.${RESET}"
echo ""

# ── Docker check ──────────────────────────────────────────────────────────────
if ! docker info &>/dev/null; then
  echo -e "${RED}❌  Docker is not running. Start Docker Desktop and re-run.${RESET}"
  exit 1
fi
echo -e "${GREEN}✓ Docker is running${RESET}"

# ── Required credentials ──────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Required ─────────────────────────────────────────────${RESET}"
echo ""

read -rp "Anthropic API key (sk-ant-...): " ANTHROPIC_API_KEY
if [[ -z "$ANTHROPIC_API_KEY" ]]; then
  echo -e "${RED}❌  Anthropic API key is required (used for extraction and query).${RESET}"
  exit 1
fi

read -rp "Project name (e.g. my_team_auth_service): " PROJECT_ID
if [[ -z "$PROJECT_ID" ]]; then
  echo -e "${RED}❌  Project name is required.${RESET}"
  exit 1
fi
# Normalise to underscore slug
PROJECT_ID="${PROJECT_ID//[^a-zA-Z0-9]/_}"

# Generate a random API key for local use
API_KEY="pbk_$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)"

# ── Write apps/api/.env ───────────────────────────────────────────────────────
ENV_FILE="apps/api/.env"

cat > "$ENV_FILE" << ENVEOF
# Generated by setup.sh on $(date)

# ── Infrastructure ──────────────────────────────────────────────────────────
REDIS_URL=redis://localhost:6379
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=password
QDRANT_URL=http://localhost:6333

# ── LLM ────────────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
LLM_PROVIDER=anthropic
LLM_MODEL=claude-haiku-4-5-20251001
EXTRACTION_MODEL=claude-haiku-4-5-20251001

# ── Auth ────────────────────────────────────────────────────────────────────
SESSION_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | base64 | head -c 44)

# ── Default project ─────────────────────────────────────────────────────────
DEFAULT_PROJECT_ID=${PROJECT_ID}

# ── GitHub (optional — add to connect GitHub signal) ────────────────────────
# GITHUB_TOKEN=ghp_...
# GITHUB_WEBHOOK_SECRET=local-dev-secret

# ── Slack (optional) ────────────────────────────────────────────────────────
# SLACK_BOT_TOKEN=xoxb-...
# SLACK_APP_TOKEN=xapp-...
# SLACK_CHANNEL_IDS=C01234,C05678

# ── Jira (optional) ─────────────────────────────────────────────────────────
# JIRA_BASE_URL=https://myorg.atlassian.net
# JIRA_WEBHOOK_SECRET=...

# ── Tuning ──────────────────────────────────────────────────────────────────
DRIFT_SEMANTIC_THRESHOLD=0.55
DRIFT_TOP_K=3
CONTEXT_BUDGET=6000
ENVEOF

echo -e "${GREEN}✓ Written apps/api/.env${RESET}"

# ── Write apps/mcp/.env ───────────────────────────────────────────────────────
cat > "apps/mcp/.env" << MCPEOF
BRAIN_API_URL=http://localhost:3001
BRAIN_API_KEY=${API_KEY}
BRAIN_AGENT_ID=claude-code
MCPEOF
echo -e "${GREEN}✓ Written apps/mcp/.env${RESET}"

# ── Install dependencies ──────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Installing dependencies ──────────────────────────────${RESET}"
npm install --silent
echo -e "${GREEN}✓ Dependencies installed${RESET}"

# ── Build MCP server ──────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Building MCP server ──────────────────────────────────${RESET}"
npm run build -w apps/mcp
chmod +x apps/mcp/dist/index.js
echo -e "${GREEN}✓ MCP server built at apps/mcp/dist/index.js${RESET}"

# ── Start everything via docker compose ───────────────────────────────────────
echo ""
echo -e "${YELLOW}── Starting infrastructure + API + workers ──────────────${RESET}"
echo "(First run builds the API image — typically 2-3 minutes)"
docker compose up -d --build
echo -e "${GREEN}✓ All services started${RESET}"

# Wait for the API to be healthy before running migrations
echo ""
echo -e "${YELLOW}── Waiting for API to be healthy ────────────────────────${RESET}"
API_TIMEOUT=120
API_ELAPSED=0
until curl -sf http://localhost:3001/health >/dev/null 2>&1; do
  if [[ $API_ELAPSED -ge $API_TIMEOUT ]]; then
    echo -e "${RED}❌  API did not become healthy within ${API_TIMEOUT}s.${RESET}"
    echo "    Check logs: docker compose logs api"
    exit 1
  fi
  sleep 2
  API_ELAPSED=$((API_ELAPSED + 2))
done
echo -e "${GREEN}✓ API is healthy (${API_ELAPSED}s)${RESET}"

# Apply Neo4j schema constraints (idempotent — safe to re-run)
echo ""
echo -e "${YELLOW}── Applying Neo4j schema constraints ───────────────────${RESET}"
npm run migrate:constraints -w apps/api 2>&1 | grep -v "^$" || true
echo -e "${GREEN}✓ Schema constraints applied${RESET}"

echo ""
echo "  - API:           http://localhost:3001"
echo "  - Web UI:        http://localhost:3000"
echo "  - Neo4j Browser: http://localhost:7474  (neo4j / password)"
echo "  - Qdrant:        http://localhost:6333"
echo "  - Workers:       normalizer, extractor, brain-writer, drift-detector"

# ── Print MCP config ──────────────────────────────────────────────────────────
MCP_ABS_PATH="$(pwd)/apps/mcp/dist/index.js"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║  Add this to ~/.claude/settings.json                     ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""
cat << MCPCONFIG
{
  "mcpServers": {
    "purpl-brain": {
      "command": "node",
      "args": ["${MCP_ABS_PATH}"],
      "env": {
        "BRAIN_API_URL": "http://localhost:3001",
        "BRAIN_API_KEY": "${API_KEY}",
        "BRAIN_AGENT_ID": "claude-code"
      }
    }
  }
}
MCPCONFIG

echo ""
echo -e "${YELLOW}For Cursor: paste the same block into .cursor/mcp.json in your project root.${RESET}"
echo -e "${YELLOW}Change BRAIN_AGENT_ID to \"cursor\" if using Cursor.${RESET}"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║  Setup complete                                          ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Paste the MCP config above into ~/.claude/settings.json"
echo ""
echo "  2. Verify the loop end-to-end:"
echo ""
echo "     BRAIN_API_KEY=${API_KEY} npm run demo:agent-memory -w apps/api"
echo ""
echo "  3. Open a Claude Code session on any repo — brain_query and"
echo "     brain_log_decision are now in the tool chain automatically."
echo ""
echo -e "${YELLOW}Tail logs:${RESET}"
echo ""
echo "  docker compose logs -f api extractor brain-writer"
echo ""
echo -e "${YELLOW}Optional — connect signal sources:${RESET}"
echo ""
echo "  GitHub:  uncomment GITHUB_TOKEN in apps/api/.env, then:"
echo "           npm run seed:github -w apps/api -- --repo org/repo"
echo ""
echo "  Slack:   uncomment SLACK_* vars in apps/api/.env, then:"
echo "           npm run worker:slack -w apps/api"
echo ""
echo "  Jira:    uncomment JIRA_* vars in apps/api/.env, then:"
echo "           npm run seed:jira -w apps/api -- --project YOUR_PROJECT"
echo ""
echo "  Docs/transcripts: see README.md for the ingest API."
echo ""
